global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: email
  routes:
    - match:
        severity: warning
      receiver: email
    - match:
        severity: critical
      receiver: slack

receivers:
  - name: email
    email_configs:
    - to: htq0505@gmail.com
      send_resolved: true
      from: prometheuscap2@gmail.com
      smarthost: smtp.gmail.com:587
      auth_username:  "prometheuscap2@gmail.com"
      auth_identity: "prometheuscap2@gmail.com"
      auth_password: "##############"
  - name: slack
    slack_configs:
    - api_url: 'https://hooks.slack.com/services/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'
      username: 'AlertManager'
      text: '{{ template "slack.custom.text" . }}'
      title: ''
      title_link: ''
      pretext: ''
      icon_url: 'https://avatars3.githubusercontent.com/u/3380462'

templates:
  - 'templates/slack.app.tmpl'