global:
  scrape_interval:     15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "localhost:9093"

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s
    scrape_timeout: 5s
    static_configs:
      - targets: ['localhost:9090']
      
  - job_name: 'redis_exporter'
    scrape_interval: 5s
    scrape_timeout: 5s
    metrics_path: "/metrics"
    static_configs:
      - targets: ['192.168.43.132:9121']

  - job_name: 'node_exporter'
    scrape_interval: 5s
    scrape_timeout: 5s
    metrics_path: "/metrics"
    static_configs:
      - targets: ['192.168.43.140:9100']

  - job_name: 'app_exporter'
    scrape_interval: 5s
    scrape_timeout: 5s
    metrics_path: "/metrics"
    static_configs:
      - targets: ['192.168.43.140:8000']

rule_files:
  - alerts/app.yaml