global:
  scrape_interval:     15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "localhost:9093"

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s
    scrape_timeout: 5s
    static_configs:
      - targets: ['localhost:9090']
      
  - job_name: 'redis_exporter' # Redis cluster monitor
    scrape_interval: 5s
    scrape_timeout: 5s
    metrics_path: "/scrape"
    static_configs:
      - targets:
        - '192.168.43.132:6379'
        - '192.168.43.132:6380'
        - '192.168.43.132:6381'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.43.132:9121

  - job_name: 'node_exporter'
    scrape_interval: 5s
    scrape_timeout: 5s
    metrics_path: "/metrics"
    static_configs:
      - targets: ['192.168.43.140:9100']

  - job_name: 'app_exporter'
    scrape_interval: 5s
    scrape_timeout: 5s
    metrics_path: "/metrics"
    static_configs:
      - targets: ['192.168.43.140:8000']

rule_files:
  - alerts/app.yaml
  - alerts/node.yaml
  - alerts/redis.yaml