groups:
  - name: application monitoring
    rules:
      - alert: InstanceDown
        expr: up == 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "Prometheus target missing (instance {{ $labels.instance }})"
          description: "A Prometheus target has disappeared. An exporter might be crashed.\n  VALUE = {{ $value }}\n  LABELS: {{ $labels.$instance }}"
      - alert: TooManyHTTPStatusCode500
        expr: increase(flask_request_count_total{http_status="500"}[10s]) > 0
        for: 10s
        labels:
          severity: critical
        annotations:
          summary: "TooManyHTTPStatusCode500 (instance {{ $labels.instance }})"
          description: "TooManyHTTPStatusCode500 >5\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
      - alert: TooManyHTTPStatusCode404
        expr: rate(flask_request_count_total{http_status="404"}[1m]) * 100 > 5
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "TooManyHTTPStatusCode404 (instance {{ $labels.instance }})"
          description: "TooManyHTTPStatusCode404 >5\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
      - alert: TooManyHTTPStatusCode401
        expr: rate(flask_request_count_total{http_status="401"}[1m]) * 100 > 5
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "TooManyHTTPStatusCode401 (instance {{ $labels.instance }})"
          description: "TooManyHTTPStatusCode401 >5\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"